version: '2'
services:
    swoft:
        container_name: swoft
        image: swoft/swoft:latest
        ports:
            - "9501:9501"
            - "8099:8099"
        volumes:
            - /data/wwwroot/blog_api_swoft:/var/www/swoft
        stdin_open: true
        tty: true
        command: php /var/www/swoft/bin/swoft start
